db.exchange.insert([{"name":"Binance","updateTime":null,"spotsVolumeUsd":17439737358.59588,"createdTime":null,"slug":"binance","homepageUrl":"https://www.binance.com/","exchangeId":270,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"Coinbase Exchange","updateTime":null,"spotsVolumeUsd":2823659047.1864266,"createdTime":null,"slug":"coinbase-exchange","homepageUrl":"https://pro.coinbase.com","exchangeId":89,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"FTX","updateTime":null,"spotsVolumeUsd":1939880916.555868,"createdTime":null,"slug":"ftx","homepageUrl":"https://ftx.com/","exchangeId":524,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"Kraken","updateTime":null,"spotsVolumeUsd":801984305.0605168,"createdTime":null,"slug":"kraken","homepageUrl":"https://www.kraken.com","exchangeId":24,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"KuCoin","updateTime":null,"spotsVolumeUsd":2473519474.2940874,"createdTime":null,"slug":"kucoin","homepageUrl":"https://www.kucoin.com","exchangeId":311,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"Gate.io","updateTime":null,"spotsVolumeUsd":1885940934.5943992,"createdTime":null,"slug":"gate-io","homepageUrl":"https://gate.io/","exchangeId":302,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"Huobi Global","updateTime":null,"spotsVolumeUsd":1993665239.7661734,"createdTime":null,"slug":"huobi-global","homepageUrl":"https://www.huobi.com/","exchangeId":102,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"Bitfinex","updateTime":null,"spotsVolumeUsd":540628634.0086255,"createdTime":null,"slug":"bitfinex","homepageUrl":"https://www.bitfinex.com","exchangeId":37,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"Gemini","updateTime":null,"spotsVolumeUsd":142646519.15725946,"createdTime":null,"slug":"gemini","homepageUrl":"https://gemini.com/","exchangeId":151,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"Binance.US","updateTime":null,"spotsVolumeUsd":330292144.8010085,"createdTime":null,"slug":"binance-us","homepageUrl":"https://www.binance.us/en","exchangeId":630,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"Crypto.com Exchange","updateTime":null,"spotsVolumeUsd":2134878743.7844493,"createdTime":null,"slug":"crypto-com-exchange","homepageUrl":"https://crypto.com/exchange","exchangeId":1149,"markets":1,"coins":1,"isActive":true,"derivativesVolumeUsd":null}])

db.crypto_currency.insert([{"name":"Bitcoin","symbol":"BTC","category":"coin","updateTime":null,"priceUsd":38693.09,"maxSupply":21000000,"totalSupply":19026118,"circulatingSupply":19026118.00,"spotsVolumeUsd":29991686115,"createdTime":null,"slug":"bitcoin","homepageUrl":"https://bitcoin.org/","cryptoCurrencyId":1,"isActive":true,"derivativesVolumeUsd":null},
{"name":"Ethereum","symbol":"ETH","category":"coin","updateTime":null,"priceUsd":2822.91,"maxSupply":null,"totalSupply":120584436,"circulatingSupply":120583295.56,"spotsVolumeUsd":18436728111,"createdTime":null,"slug":"ethereum","homepageUrl":"https://www.ethereum.org/","cryptoCurrencyId":1027,"isActive":true,"derivativesVolumeUsd":null},
{"name":"Tether","symbol":"USDT","category":"token","updateTime":null,"priceUsd":1.00,"maxSupply":null,"totalSupply":85713951816,"circulatingSupply":85150000000,"spotsVolumeUsd":66768156071,"createdTime":null,"slug":"tether","homepageUrl":"https://tether.to","cryptoCurrencyId":825,"isActive":true,"derivativesVolumeUsd":null}
])

db.market.insert([{"marketId":1,"exchangeId":270,"baseCryptoCurrencyId":1,"baseSymbol":"BTC","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":38693.09,"priceNative":38693.09,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":2,"exchangeId":270,"baseCryptoCurrencyId":1027,"baseSymbol":"ETH","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":2822.91,"priceNative":2822.91,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":3,"exchangeId":89,"baseCryptoCurrencyId":1,"baseSymbol":"BTC","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":38693.09,"priceNative":38693.09,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":4,"exchangeId":89,"baseCryptoCurrencyId":1027,"baseSymbol":"ETH","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":2822.91,"priceNative":2822.91,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":5,"exchangeId":524,"baseCryptoCurrencyId":1,"baseSymbol":"BTC","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":38693.09,"priceNative":38693.09,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":6,"exchangeId":524,"baseCryptoCurrencyId":1027,"baseSymbol":"ETH","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":2822.91,"priceNative":2822.91,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":7,"exchangeId":24,"baseCryptoCurrencyId":1,"baseSymbol":"BTC","baseSymbolOverride":"XBT","mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":38693.09,"priceNative":38693.09,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":8,"exchangeId":24,"baseCryptoCurrencyId":1027,"baseSymbol":"ETH","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":2822.91,"priceNative":2822.91,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":9,"exchangeId":311,"baseCryptoCurrencyId":1,"baseSymbol":"BTC","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":38693.09,"priceNative":38693.09,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":10,"exchangeId":311,"baseCryptoCurrencyId":1027,"baseSymbol":"ETH","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":2822.91,"priceNative":2822.91,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":11,"exchangeId":302,"baseCryptoCurrencyId":1,"baseSymbol":"BTC","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":38693.09,"priceNative":38693.09,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":12,"exchangeId":302,"baseCryptoCurrencyId":1027,"baseSymbol":"ETH","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":2822.91,"priceNative":2822.91,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":13,"exchangeId":102,"baseCryptoCurrencyId":1,"baseSymbol":"BTC","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":38693.09,"priceNative":38693.09,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":14,"exchangeId":102,"baseCryptoCurrencyId":1027,"baseSymbol":"ETH","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":2822.91,"priceNative":2822.91,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":15,"exchangeId":37,"baseCryptoCurrencyId":1,"baseSymbol":"BTC","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":"UST","category":"Spot","updateTime":null,"priceUsd":38693.09,"priceNative":38693.09,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":16,"exchangeId":37,"baseCryptoCurrencyId":1027,"baseSymbol":"ETH","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":"UST","category":"Spot","updateTime":null,"priceUsd":2822.91,"priceNative":2822.91,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":17,"exchangeId":630,"baseCryptoCurrencyId":1,"baseSymbol":"BTC","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":38693.09,"priceNative":38693.09,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":18,"exchangeId":630,"baseCryptoCurrencyId":1027,"baseSymbol":"ETH","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":2822.91,"priceNative":2822.91,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":19,"exchangeId":1149,"baseCryptoCurrencyId":1,"baseSymbol":"BTC","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":38693.09,"priceNative":38693.09,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true},
{"marketId":20,"exchangeId":1149,"baseCryptoCurrencyId":1027,"baseSymbol":"ETH","baseSymbolOverride":null,"mainCryptoCurrencyId":825,"mainSymbol":"USDT","mainSymbolOverride":null,"category":"Spot","updateTime":null,"priceUsd":2822.91,"priceNative":2822.91,"volumeBase":null,"volumeMain":null,"volumeUsd":null,"createdTime":null,"isActive":true}
])

